# Prometheus配置文件

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'blog-monitor'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # Spring Boot应用监控
  - job_name: 'blog-backend'
    static_configs:
      - targets: ['blog-backend-prod:8081']
    scrape_interval: 10s
    metrics_path: /actuator/prometheus
    scrape_timeout: 5s

  # Nginx监控
  - job_name: 'nginx'
    static_configs:
      - targets: ['blog-frontend-prod:80']
    scrape_interval: 10s
    metrics_path: /nginx_status
    scrape_timeout: 5s

  # MySQL监控 (需要mysql_exporter)
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-exporter:9104']
    scrape_interval: 10s
    scrape_timeout: 5s

  # Redis监控 (需要redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 10s
    scrape_timeout: 5s

  # Node Exporter (系统监控)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s
    scrape_timeout: 5s

  # Docker监控
  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 10s
    scrape_timeout: 5s