server:
  port: 8081
  servlet:
    context-path: /api

# Spring配置
spring:
  # 数据源配置 - 统一使用MySQL数据库
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: qhdx2023-
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  
  # JPA配置
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    
  # Spring MVC配置
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # 缓存配置
  cache:
    type: simple
    cache-names:
      - articles
      - categories
      - tags
      - popularArticles
      - searchSuggestions
      - userProfiles
      

  
  # 异步配置
  task:
    execution:
      pool:
        core-size: 5
        max-size: 20
        queue-capacity: 100
      thread-name-prefix: blog-task-
    scheduling:
      pool:
        size: 5
      thread-name-prefix: blog-scheduling-

# JWT配置
jwt:
  secret: blog-secret-key
  expiration: 86400000  # 24小时

# 日志配置
logging:
  level:
    com.blog: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.springframework.cache: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 性能监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,httptrace,caches
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99

# 文件上传配置
file:
  upload-dir: ./uploads
  max-size: 10MB
  allowed-types: image/jpeg,image/png,image/gif