# 生产环境配置
spring:
  profiles:
    active: prod
  
  # 数据源配置
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:mysql}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:blog}?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:bloguser}
    password: ${MYSQL_PASSWORD:blog123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: BlogHikariCP
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      leak-detection-threshold: 60000
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
        use_sql_comments: false
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
  
  # Redis配置
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: 2000ms
    database: 0
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
        max-wait: 2000ms
      shutdown-timeout: 100ms
  
  # 缓存配置
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: false
      use-key-prefix: true
      key-prefix: "blog:cache:"
  
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      enabled: true
  
  # 邮件配置
  mail:
    host: ${SMTP_HOST:smtp.qq.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: ${SMTP_HOST:smtp.qq.com}
  
  # Jackson配置
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

# 服务器配置
server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

# 日志配置
logging:
  level:
    root: INFO
    com.blog: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /app/logs/blog.log
    max-size: 100MB
    max-history: 30
    total-size-cap: 1GB

# Actuator配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: when-authorized
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99
  health:
    redis:
      enabled: true
    db:
      enabled: true
    diskspace:
      enabled: true
      threshold: 1GB

# 应用配置
blog:
  # JWT配置
  jwt:
    secret: ${JWT_SECRET:your-secret-key-here-should-be-very-long-and-random}
    expiration: 86400000  # 24小时
    refresh-expiration: 604800000  # 7天
  
  # 文件上传配置
  upload:
    path: ${FILE_UPLOAD_PATH:/app/uploads}
    max-size: 20971520  # 20MB
    allowed-types: jpg,jpeg,png,gif,pdf,doc,docx,txt,md
    image-max-width: 1920
    image-max-height: 1080
    image-quality: 0.8
  
  # 安全配置
  security:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600
    rate-limit:
      enabled: true
      requests-per-minute: 60
      burst-capacity: 100
  
  # 缓存配置
  cache:
    default-ttl: 3600  # 1小时
    article-ttl: 7200  # 2小时
    category-ttl: 86400  # 24小时
    user-ttl: 1800  # 30分钟
  
  # 邮件配置
  mail:
    from: ${MAIL_FROM:noreply@yourdomain.com}
    from-name: ${MAIL_FROM_NAME:博客系统}
    enabled: ${MAIL_ENABLED:false}
  
  # 第三方服务配置
  oss:
    # 阿里云OSS
    aliyun:
      enabled: ${ALIYUN_OSS_ENABLED:false}
      endpoint: ${ALIYUN_OSS_ENDPOINT:}
      access-key-id: ${ALIYUN_OSS_ACCESS_KEY_ID:}
      access-key-secret: ${ALIYUN_OSS_ACCESS_KEY_SECRET:}
      bucket-name: ${ALIYUN_OSS_BUCKET_NAME:}
    # 腾讯云COS
    tencent:
      enabled: ${TENCENT_COS_ENABLED:false}
      secret-id: ${TENCENT_COS_SECRET_ID:}
      secret-key: ${TENCENT_COS_SECRET_KEY:}
      region: ${TENCENT_COS_REGION:}
      bucket: ${TENCENT_COS_BUCKET:}
  
  # 系统配置
  system:
    name: ${SYSTEM_NAME:博客系统}
    version: ${SYSTEM_VERSION:1.0.0}
    description: ${SYSTEM_DESCRIPTION:基于Vue+Spring Boot的博客系统}
    author: ${SYSTEM_AUTHOR:博客管理员}
    website: ${SYSTEM_WEBSITE:https://yourdomain.com}
    icp: ${SYSTEM_ICP:}
    
  # 性能配置
  performance:
    async:
      core-pool-size: 5
      max-pool-size: 20
      queue-capacity: 100
      thread-name-prefix: "blog-async-"
    
  # 监控配置
  monitoring:
    enabled: true
    slow-query-threshold: 1000  # 慢查询阈值(毫秒)
    error-rate-threshold: 0.05  # 错误率阈值
    response-time-threshold: 2000  # 响应时间阈值(毫秒)